In [1]:
P = [0.2 0.4 0.4;
     0.1 0.3 0.6;
     0.7 0.1 0.2]

3×3 Matrix{Float64}:
 0.2  0.4  0.4
 0.1  0.3  0.6
 0.7  0.1  0.2

In [2]:
P*ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

${\mathbf 1}$ is a column vector of $1$ values.

$$
\pi P = \pi
$$

$$
\pi {\mathbf 1} = {\mathbf 1}^\top \pi^T = 1  \qquad (\pi_1 + \pi_2 + \pi_3 = 1)
$$

First equation:
$$
\pi P = \pi I
$$

$$
\pi P - \pi I = 0
$$


$$
\pi (P - I) = 0
$$

$$
(P^\top - I) \pi^\top = 0
\qquad (Like: A x = b)
$$

In [5]:
using LinearAlgebra

In [15]:
A = P'-I

3×3 Matrix{Float64}:
 -0.8   0.1   0.7
  0.4  -0.7   0.1
  0.4   0.6  -0.8

In [16]:
rank(A)

2

In [17]:
A[1,:] = ones(3)  #Replaced first row by vector of 1's (but could have done it to any arbitrary row)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [19]:
A

3×3 Matrix{Float64}:
 1.0   1.0   1.0
 0.4  -0.7   0.1
 0.4   0.6  -0.8

In [20]:
b = [1,0,0]  #has a '1' in the position matching the row I replaced

3-element Vector{Int64}:
 1
 0
 0

In [22]:
#Now I can solve Ax = b
x = A \ b

3-element Vector{Float64}:
 0.36231884057971026
 0.2608695652173913
 0.3768115942028985

In [23]:
my_pi = x'

1×3 adjoint(::Vector{Float64}) with eltype Float64:
 0.362319  0.26087  0.376812

In [24]:
my_pi*P

1×3 adjoint(::Vector{Float64}) with eltype Float64:
 0.362319  0.26087  0.376812

In [25]:
sum(my_pi)

1.0

## Eigenvalues...

In [26]:
eigvals(P)

3-element Vector{ComplexF64}:
 -0.15000000000000005 - 0.2397915761656359im
 -0.15000000000000005 + 0.2397915761656359im
   1.0000000000000009 + 0.0im

In [27]:
eigvecs(P)

3×3 Matrix{ComplexF64}:
 -0.0504156-0.349245im  -0.0504156+0.349245im  -0.57735+0.0im
  -0.694615-0.0im        -0.694615+0.0im       -0.57735+0.0im
   0.529364+0.335812im    0.529364-0.335812im  -0.57735+0.0im

In [28]:
eigvecs(P')

3×3 Matrix{ComplexF64}:
 -0.738549-0.0im       -0.738549+0.0im       0.620174+0.0im
   0.43082-0.295163im    0.43082+0.295163im  0.446525+0.0im
  0.307729+0.295163im   0.307729-0.295163im  0.644981+0.0im

In [32]:
real.(eigvecs(P')[:,3])/sum(real.(eigvecs(P')[:,3]))

3-element Vector{Float64}:
 0.36231884057971003
 0.26086956521739124
 0.37681159420289867

In [33]:
my_pi

1×3 adjoint(::Vector{Float64}) with eltype Float64:
 0.362319  0.26087  0.376812